- name: Add qBittorrent apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 401E8827DA4E93E44C7D01E6D35164147CA69FC4
- name: Add qBittorrent apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu jammy main"
    state: present
- name: Install qbittorrent-nox
  ansible.builtin.apt:
    name: qbittorrent-nox
    state: latest
  notify: restart qBittorrent
- name: Ensure config directory exists.
  ansible.builtin.file:
    path: "/home/media/.config/qBittorrent"
    state: directory
    recurse: yes
    owner: media
    group: media
- name: Copy qBittorrent config file if not exists
  ansible.builtin.copy:
    src: "./qBittorrent/qBittorrent.conf"
    dest: "/home/media/.config/qBittorrent/qBittorrent.conf"
    force: no # copies file when no dest file exists
    owner: root
    group: root
    mode: 0644
  notify:
    - restart qBittorrent
- name: Copy qBittorrent service file if not exists
  ansible.builtin.copy:
    src: "./qBittorrent/qbittorrent-nox@.service"
    dest: "/usr/lib/systemd/system/qbittorrent-nox@.service"
    force: no # copies file when no dest file exists
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart qBittorrent
- name: Ensure qBittorrent is enabled at boot.
  ansible.builtin.systemd:
    name: qbittorrent-nox@media.service
    enabled: yes
    daemon_reload: yes
  notify:
    - restart qBittorrent
- name: Ensure qBittorrent is started.
  ansible.builtin.systemd:
    name: qbittorrent-nox@media.service
    state: started
