- name: All tasks
  hosts: "{{ target|default('znas') }}"
  tasks:
    - name: System
      ansible.builtin.import_tasks:
        file: system.yml
    - name: Users
      ansible.builtin.import_tasks:
        file: users.yml
    - name: Media
      ansible.builtin.import_tasks:
        file: media.yml
    - name: Syncthing
      ansible.builtin.import_tasks:
        file: syncthing.yml
    - name: Samba
      ansible.builtin.import_tasks:
        file: samba.yml
